language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test -- --coverage
  - npm build
after_success:
  - coveralls < coverage/lcov.info
notifications:
  email: false
