language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test -- --coverage
  - npm build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT 
notifications:
  email: false
