language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run lint
  - npm test -- --coverage
  - npm build
after_script:
  - nyc report --reporter=text-lcov | coveralls
notifications:
  email: false
